# Generated by Django 5.0.6 on 2024-06-16 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=64)),
                ('cellphone', models.CharField(max_length=11, unique=True)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='users/profile/%Y/%m/%d/')),
                ('username', models.SlugField(unique=True)),
                ('work_type', models.CharField(choices=[('CPF', 'CPF'), ('CNPJ', 'CNPJ')])),
                ('cnpj', models.CharField(max_length=14)),
                ('cpf', models.CharField(max_length=11)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Expertise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expertises', to='demo.service')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='demo.service')),
            ],
        ),
        migrations.CreateModel(
            name='OfferedService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=600)),
                ('service', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='offered_services', to='demo.service')),
                ('service_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offered_services', to='demo.serviceprovider')),
            ],
        ),
    ]
