# Generated by Django 5.0.6 on 2024-06-16 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceprovider',
            name='cnpj',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='cpf',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
