# Generated by Django 5.0.6 on 2024-06-16 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0003_remove_servicecategory_service_service_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expertise',
            name='service',
        ),
        migrations.AddField(
            model_name='service',
            name='expertise',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='demo.expertise'),
            preserve_default=False,
        ),
    ]
