# Generated by Django 5.0.6 on 2024-06-16 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0004_remove_expertise_service_service_expertise'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offeredservice',
            name='service_provider',
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='offered_services',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='demo.offeredservice'),
            preserve_default=False,
        ),
    ]
