# Generated by Django 5.0.6 on 2024-08-18 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0006_remove_serviceprovider_offered_services_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expertise',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='servicecategory',
            old_name='title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='service',
            name='expertise',
        ),
        migrations.AddField(
            model_name='expertise',
            name='service',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='expertises', to='demo.service'),
            preserve_default=False,
        ),
    ]
