# Generated by Django 5.0.6 on 2024-08-18 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0007_rename_title_expertise_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ServiceCategory',
            new_name='Category',
        ),
    ]
