# Generated by Django 5.1.5 on 2025-03-02 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0011_remove_offeredservice_services_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='role',
            field=models.CharField(choices=[('service_provider', 'Service Provider'), ('customer', 'Customer')], default='service_provider', max_length=20),
        ),
    ]
