# Generated by Django 5.1.5 on 2025-03-02 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0012_serviceprovider_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceprovider',
            name='password',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='role',
            field=models.CharField(choices=[('service_provider', 'Service Provider'), ('customer', 'Customer')], default='service_provider'),
        ),
    ]
