# Generated by Django 5.1.5 on 2025-03-02 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0013_alter_serviceprovider_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField()),
                ('cellphone', models.CharField(max_length=11, unique=True)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='users/profile/%Y/%m/%d/')),
                ('username', models.SlugField(unique=True)),
                ('role', models.CharField(choices=[('service_provider', 'Service Provider'), ('customer', 'Customer')], default='service_provider')),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=2)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
