# Generated by Django 5.0.6 on 2025-03-08 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0015_alter_customer_options_alter_serviceprovider_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cellphone',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
